### PR TITLE
WIP: Restore full test suite on CI

### PR DESCRIPTION
**Pull request by rmg**

### CODE REVIEW

**Comment by rmg** [comment]
@superkhau @qpresley it looks like the only reason CI is failing for this module now is that we've got concurrent tests running against a single shared DB. I've serialized and throttled each environment, but unfortunately they don't coordinate with each other so we end up with 2 tests running at the same time (instead of 8), which is still too many for the way these tests are written.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by 0candy** [comment]
@slnode test please

**Comment by qpresley** [comment]
test please

**Comment by qpresley** [comment]
test please

**Comment by qpresley** [comment]
Latest PR CI tests ran fine.  Closing this PR without merging.

**Pull request closed without merging**
