### PR TITLE
Refactor discovery

### PR DESCRIPTION
**Pull request by jannyHou**
### Description
Refactor discovery

#### Related issues
connect to https://github.com/strongloop/loopback-connector/issues/15

### CODE REVIEW

**Comment by jannyHou** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by jannyHou** [comment]
Upgrading `loopback-ibmdb` to use `loopback-connector@3.x`
Otherwise CI could not test with the latest master code in `loopback-connector`
See pr https://github.com/strongloop/loopback-ibmdb/pull/39

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
Failures are the same as master, not related to discovery.
Created an issue to track the test cases fix: https://github.com/strongloop-internal/scrum-apex/issues/104

**Pull request merged**
