### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by dhmlau**

### CODE REVIEW

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@rmg , looks like there's still connection problem to the dashdb instance.  I'm wondering if it would be easier to create another dashdb instance.

**Comment by dhmlau** [comment]
With #72, I can close this PR.

**Pull request closed without merging**
