### PR TITLE
Enable pooling

### PR DESCRIPTION
**Pull request by qpresley**
PR includes the enabling of connection pooling by removal of creating a generic connection in the initialization function as well as the removal of lazy connect tests as there is no such thing as lazy connect in the IBM drivers.

### CODE REVIEW

**Comment by qpresley** [comment]
@jannyHou PTAL

**Comment by jannyHou** [comment]
LGTM

**Comment by superkhau** [comment]
@jannyHou FYI, not LGTM, this should've been merged into 1.x instead (and forward ported to 3.x or merged into master and backported to 1.x) -- however, this should have been fixed by @b-admike via interrupt.

**Comment by jannyHou** [comment]
@superkhau This pr is made before the release of 3.x, so there is no concern of merging it to which branch. All released versions(1.x) are on master.

**Comment by superkhau** [comment]
@jannyHou The concern is @qpresley released to npmjs from master this morning -- which required us to to unpublish 3.0.0 from NPMJS. If we only merged to 1.x, the fire this morning wouldn't have happened at all.

**Pull request merged**
